name: GitHub Metrics
on:
  schedule: [{ cron: "0 */12 * * *" }]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: LukaszMateuszSobczak
          filename: metrics.svg
          base: header, activity, repositories, metadata

          plugin_languages: yes
          plugin_languages_threshold: 2%
          plugin_languages_limit: 10

          plugin_stars: yes
          plugin_followup: yes
          plugin_activity: yes
          plugin_habits: yes

          config_timezone: Europe/Warsaw
          config_display: large
